// <auto-generated />

using System;
using System.Linq;
using System.Collections.Generic;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Microsoft.Crm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Messages;
using Microsoft.Xrm.Sdk.Metadata;
using Microsoft.Xrm.Sdk.Client;
using System.Threading.Tasks;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace MSCPS.FieldSericeMigration.Plugins.ProxyClasses
{
    [EntityLogicalNameAttribute("msdyn_agreementinvoiceproduct")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XrmToolkit", "4.0")]
    [DataContract(Name = "Entity", Namespace = "http://schemas.microsoft.com/xrm/2011/Contracts")]
    public partial class msdyn_agreementinvoiceproduct : BaseProxyClass
    {
        public new const string LogicalName = "msdyn_agreementinvoiceproduct";
        public const int ObjectTypeCode = 10061;
        public const string PrimaryIdAttribute = "msdyn_agreementinvoiceproductid";
        public const string PrimaryNameAttribute = "msdyn_name";
        
        static msdyn_agreementinvoiceproduct()
        {
            BaseProxyClass.RegisterProxyType(typeof(msdyn_agreementinvoiceproduct), "msdyn_agreementinvoiceproduct");
            _textOptions = new Dictionary<string, eTextOptions>();
            _numberOptions = new Dictionary<string, eNumberOptions>();
            _errorStrings = new Dictionary<string, string>();
            TextError = "The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.";
            NumberError = "The value for attribute '{0}' must be between {2} and {3}. The value is {1}";
        }
        public msdyn_agreementinvoiceproduct() : base(new Entity("msdyn_agreementinvoiceproduct")) { }
        public msdyn_agreementinvoiceproduct(Entity original) : base(original) { }
        public static string GetLogicalName() { return BaseProxyClass.GetLogicalName<msdyn_agreementinvoiceproduct>(); }
        /// <summary>
        /// Action to perform when the string value is greater than the allowed length.
        /// <para>This is the default for any string attribute in this Entity</para>
        /// </summary>
        public static eTextOptions TextOptions { get; set; }
        private static Dictionary<string, eTextOptions> _textOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater than the allowed length
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater than the allowed length</param>
        /// <param name="errorString">Optional: Error to throw if the eTextOptions == ThrowError
        /// <para>If nothing is specified then the 'TextError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </param>
        public static void SetTextOptions(string logicalName, eTextOptions options, string errorString = null)
        {
            if (_textOptions.ContainsKey(logicalName)) { _textOptions[logicalName] = options; }
            else { _textOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eTextOptions GetTextOptions(string logicalName)
        {
            if (_textOptions.ContainsKey(logicalName)) { return _textOptions[logicalName]; }
            return TextOptions;
        }
        /// <summary>
        /// Action to perform when the number value is greater or less than the allowed value.
        /// <para>This is the default for any int, decimal, double, or money attribute in this Entity</para>
        /// </summary>
        public static eNumberOptions NumberOptions { get; set; }
        private static Dictionary<string, eNumberOptions> _numberOptions;
        /// <summary>
        /// Use this to set an action and error string when a value is greater or less than the allowed value
        /// </summary>
        /// <param name="logicalName">Name of Attribute</param>
        /// <param name="options">Action to perform when the value is greater or less than the allowed value</param>
        /// <param name="errorString">Optional: Error to throw if the eNumberOptions == ThrowError
        /// <para>If nothing is specified then the 'NumberError' string is used.</para>
        /// <para>You may use the following parameters:</para>
        /// <para>{0} = Attribute Logical Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </param>
        public static void SetNumberOptions(string logicalName, eNumberOptions options, string errorString = null)
        {
            if (_numberOptions.ContainsKey(logicalName)) { _numberOptions[logicalName] = options; }
            else { _numberOptions.Add(logicalName, options); }
            if (!string.IsNullOrEmpty(errorString))
            {
                if (_errorStrings.ContainsKey(logicalName)) { _errorStrings[logicalName] = errorString; }
                else { _errorStrings.Add(logicalName, errorString); }
            }
            else if (_errorStrings.ContainsKey(logicalName)) { _errorStrings.Remove(logicalName); }
        }
        protected override eNumberOptions GetNumberOptions(string logicalName)
        {
            if (_numberOptions.ContainsKey(logicalName)) { return _numberOptions[logicalName]; }
            return NumberOptions;
        }
        private static Dictionary<string, string> _errorStrings;
        protected override string GetErrorString(string attributeName, BaseProxyClass.eErrorType defaultErrorType)
        {
            if (_errorStrings.ContainsKey(attributeName))
            {
                return _errorStrings[attributeName];
            }
            return defaultErrorType == BaseProxyClass.eErrorType.Text ? TextError : NumberError;
        }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' cannot be longer than {3} characters. The length of the value is {2} characters.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Length</para>
        /// <para>{3} = Max Length</para>
        /// </summary>
        public static string TextError { get; set; }
        /// <summary>
        /// <para>Default error string is: The value for attribute '{0}' must be between {2} and {3}. The value is {1}.</para>
        /// <para>You may use the following parameters</para>
        /// <para>{0} = Attribute Name</para>
        /// <para>{1} = Value</para>
        /// <para>{2} = Min Value</para>
        /// <para>{3} = Max Value</para>
        /// </summary>
        public static string NumberError { get; set; }

        ///<summary>
///<para>Logical Name: utc_invoicefrequencyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("utc_invoicefrequencyname")]
public string utc_invoicefrequencyname
{
	get { return this.GetPropertyValue<string>("utc_invoicefrequencyname"); }
}
///<summary>
///<para>Logical Name: owneridtype</para>
///</summary>
[AttributeLogicalNameAttribute("owneridtype")]
public string owneridtype
{
	get { return this.GetPropertyValue<string>("owneridtype"); }
	set { this.SetPropertyValue<string>("owneridtype", value, "owneridtype"); }
}
///<summary>
///<para>Logical Name: utc_changetypename</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("utc_changetypename")]
public string utc_changetypename
{
	get { return this.GetPropertyValue<string>("utc_changetypename"); }
}
///<summary>
///<para>Logical Name: modifiedbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedbyname")]
public string modifiedbyname
{
	get { return this.GetPropertyValue<string>("modifiedbyname"); }
}
///<summary>
///<para>Logical Name: owneridname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("owneridname")]
public string owneridname
{
	get { return this.GetPropertyValue<string>("owneridname"); }
}
///<summary>
///<para>Logical Name: createdonbehalfbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
public string createdonbehalfbyyominame
{
	get { return this.GetPropertyValue<string>("createdonbehalfbyyominame"); }
}
///<summary>
///<para>Logical Name: utc_customerequipmentname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("utc_customerequipmentname")]
public string utc_customerequipmentname
{
	get { return this.GetPropertyValue<string>("utc_customerequipmentname"); }
}
///<summary>
///<para>Logical Name: utc_changereasonname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("utc_changereasonname")]
public string utc_changereasonname
{
	get { return this.GetPropertyValue<string>("utc_changereasonname"); }
}
///<summary>
///<para>Logical Name: createdonbehalfbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfbyname")]
public string createdonbehalfbyname
{
	get { return this.GetPropertyValue<string>("createdonbehalfbyname"); }
}
///<summary>
///<para>Logical Name: createdbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdbyyominame")]
public string createdbyyominame
{
	get { return this.GetPropertyValue<string>("createdbyyominame"); }
}
///<summary>
///<para>Logical Name: msdyn_unitname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_unitname")]
public string msdyn_unitname
{
	get { return this.GetPropertyValue<string>("msdyn_unitname"); }
}
///<summary>
///<para>Logical Name: msdyn_agreementname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_agreementname")]
public string msdyn_agreementname
{
	get { return this.GetPropertyValue<string>("msdyn_agreementname"); }
}
///<summary>
///<para>Logical Name: owneridyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("owneridyominame")]
public string owneridyominame
{
	get { return this.GetPropertyValue<string>("owneridyominame"); }
}
///<summary>
///<para>Logical Name: msdyn_productname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_productname")]
public string msdyn_productname
{
	get { return this.GetPropertyValue<string>("msdyn_productname"); }
}
///<summary>
///<para>Logical Name: createdbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("createdbyname")]
public string createdbyname
{
	get { return this.GetPropertyValue<string>("createdbyname"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfbyname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
public string modifiedonbehalfbyname
{
	get { return this.GetPropertyValue<string>("modifiedonbehalfbyname"); }
}
///<summary>
///<para>Logical Name: msdyn_pricelistname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_pricelistname")]
public string msdyn_pricelistname
{
	get { return this.GetPropertyValue<string>("msdyn_pricelistname"); }
}
///<summary>
///<para>Logical Name: transactioncurrencyidname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("transactioncurrencyidname")]
public string transactioncurrencyidname
{
	get { return this.GetPropertyValue<string>("transactioncurrencyidname"); }
}
///<summary>
///<para>Logical Name: msdyn_agreementinvoicesetupname</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_agreementinvoicesetupname")]
public string msdyn_agreementinvoicesetupname
{
	get { return this.GetPropertyValue<string>("msdyn_agreementinvoicesetupname"); }
}
///<summary>
///<para>Logical Name: modifiedbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedbyyominame")]
public string modifiedbyyominame
{
	get { return this.GetPropertyValue<string>("modifiedbyyominame"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfbyyominame</para>
///<para>Max Length: 100 characters</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
public string modifiedonbehalfbyyominame
{
	get { return this.GetPropertyValue<string>("modifiedonbehalfbyyominame"); }
}
///<summary>
///<para>Logical Name: msdyn_agreement</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_agreement")]
public EntityReference msdyn_agreement
{
	get { return this.GetPropertyValue<EntityReference>("msdyn_agreement"); }
	set { this.SetPropertyValue<EntityReference>("msdyn_agreement", value, "msdyn_agreement"); }
}
///<summary>
///<para>Key Property (Uniqueidentifier)</para>
///<para>Logical Name: msdyn_agreementinvoiceproductid</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_agreementinvoiceproductid")]
public Guid msdyn_agreementinvoiceproductid
{
	get
	{
		return base.Id;
	}
	set
	{
		base.Id = value;
		base.SetPropertyValue("msdyn_agreementinvoiceproductid", value, "msdyn_agreementinvoiceproductid");
	}
}
///<summary>
///<para>Logical Name: msdyn_agreementinvoicesetup</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_agreementinvoicesetup")]
public EntityReference msdyn_agreementinvoicesetup
{
	get { return this.GetPropertyValue<EntityReference>("msdyn_agreementinvoicesetup"); }
	set { this.SetPropertyValue<EntityReference>("msdyn_agreementinvoicesetup", value, "msdyn_agreementinvoicesetup"); }
}
/// <summary>
///Logical Name: utc_billingtype
/// </summary>
[AttributeLogicalNameAttribute("utc_billingtype")]
public eInvoiceBillingType? utc_billingtype
{
	get
	{
		if (utc_billingtype_OptionSetValue != null) { return (eInvoiceBillingType)utc_billingtype_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.utc_billingtype_OptionSetValue = new OptionSetValue((int)value); }
		else this.utc_billingtype_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: utc_billingtype</para>
///</summary>
[AttributeLogicalNameAttribute("utc_billingtype")]
public OptionSetValue utc_billingtype_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("utc_billingtype"); }
	set { this.SetPropertyValue<OptionSetValue>("utc_billingtype", value, "utc_billingtype_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string utc_billingtype_Text(IOrganizationService Service)
{
	return this.utc_billingtype_OptionSetValue.GetOptionSetText(Service, this, "utc_billingtype");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string utc_billingtype_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.utc_billingtype_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: utc_bypasscascadeownership</para>
///<para>True = Yes</para>
///<para>False = No</para>
///</summary>
[AttributeLogicalNameAttribute("utc_bypasscascadeownership")]
public bool? utc_bypasscascadeownership
{
	get { return this.GetPropertyValue<bool?>("utc_bypasscascadeownership"); }
	set { this.SetPropertyValue<bool?>("utc_bypasscascadeownership", value, "utc_bypasscascadeownership"); }
}
///<summary>
///<para>Logical Name: utc_changecomments</para>
///<para>Max Length: 2000 characters</para>
///</summary>
[AttributeLogicalNameAttribute("utc_changecomments")]
public string utc_changecomments
{
	get { return this.GetPropertyValue<string>("utc_changecomments"); }
	set { this.SetPropertyValue("utc_changecomments", value, 2000, "utc_changecomments"); }
}
///<summary>
///<para>Logical Name: utc_changereason</para>
///</summary>
[AttributeLogicalNameAttribute("utc_changereason")]
public EntityReference utc_changereason
{
	get { return this.GetPropertyValue<EntityReference>("utc_changereason"); }
	set { this.SetPropertyValue<EntityReference>("utc_changereason", value, "utc_changereason"); }
}
///<summary>
///<para>Logical Name: utc_changetype</para>
///</summary>
[AttributeLogicalNameAttribute("utc_changetype")]
public EntityReference utc_changetype
{
	get { return this.GetPropertyValue<EntityReference>("utc_changetype"); }
	set { this.SetPropertyValue<EntityReference>("utc_changetype", value, "utc_changetype"); }
}
///<summary>
///<para>Logical Name: createdby</para>
///</summary>
[AttributeLogicalNameAttribute("createdby")]
public EntityReference createdby
{
	get { return this.GetPropertyValue<EntityReference>("createdby"); }
}
///<summary>
///<para>Logical Name: createdonbehalfby</para>
///</summary>
[AttributeLogicalNameAttribute("createdonbehalfby")]
public EntityReference createdonbehalfby
{
	get { return this.GetPropertyValue<EntityReference>("createdonbehalfby"); }
}
///<summary>
///<para>Logical Name: createdon</para>
///</summary>
[AttributeLogicalNameAttribute("createdon")]
public DateTime? createdon
{
	get { return this.GetPropertyValue<DateTime?>("createdon"); }
}
///<summary>
///<para>Logical Name: transactioncurrencyid</para>
///</summary>
[AttributeLogicalNameAttribute("transactioncurrencyid")]
public EntityReference transactioncurrencyid
{
	get { return this.GetPropertyValue<EntityReference>("transactioncurrencyid"); }
	set { this.SetPropertyValue<EntityReference>("transactioncurrencyid", value, "transactioncurrencyid"); }
}
///<summary>
///<para>Logical Name: utc_customerequipment</para>
///</summary>
[AttributeLogicalNameAttribute("utc_customerequipment")]
public EntityReference utc_customerequipment
{
	get { return this.GetPropertyValue<EntityReference>("utc_customerequipment"); }
	set { this.SetPropertyValue<EntityReference>("utc_customerequipment", value, "utc_customerequipment"); }
}
///<summary>
///<para>Logical Name: exchangerate</para>
///<para>Minimum Value: 0.0000000001</para>
///<para>Maximum Value: 100000000000</para>
///<para>Precision: 10</para>
///</summary>
[AttributeLogicalNameAttribute("exchangerate")]
public decimal? exchangerate
{
	get { return this.GetPropertyValue<decimal?>("exchangerate"); }
}
///<summary>
///<para>Logical Name: importsequencenumber</para>
///<para>Minimum Value: -2147483648</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("importsequencenumber")]
public int? importsequencenumber
{
	get { return this.GetPropertyValue<int?>("importsequencenumber"); }
	set { this.SetPropertyValue("importsequencenumber", (int?)value, (int)-2147483648, (int)2147483647, "importsequencenumber"); }
}
///<summary>
///<para>Logical Name: utc_invoicefrequency</para>
///</summary>
[AttributeLogicalNameAttribute("utc_invoicefrequency")]
public EntityReference utc_invoicefrequency
{
	get { return this.GetPropertyValue<EntityReference>("utc_invoicefrequency"); }
	set { this.SetPropertyValue<EntityReference>("utc_invoicefrequency", value, "utc_invoicefrequency"); }
}
///<summary>
///<para>Logical Name: utc_invoicegenerationoverride</para>
///<para>Minimum Value: 0</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("utc_invoicegenerationoverride")]
public int? utc_invoicegenerationoverride
{
	get { return this.GetPropertyValue<int?>("utc_invoicegenerationoverride"); }
	set { this.SetPropertyValue("utc_invoicegenerationoverride", (int?)value, (int)0, (int)2147483647, "utc_invoicegenerationoverride"); }
}
/// <summary>
///Logical Name: utc_invoicegenerationoverridetype
/// </summary>
[AttributeLogicalNameAttribute("utc_invoicegenerationoverridetype")]
public eInvoiceGenerationOverrideType? utc_invoicegenerationoverridetype
{
	get
	{
		if (utc_invoicegenerationoverridetype_OptionSetValue != null) { return (eInvoiceGenerationOverrideType)utc_invoicegenerationoverridetype_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.utc_invoicegenerationoverridetype_OptionSetValue = new OptionSetValue((int)value); }
		else this.utc_invoicegenerationoverridetype_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: utc_invoicegenerationoverridetype</para>
///</summary>
[AttributeLogicalNameAttribute("utc_invoicegenerationoverridetype")]
public OptionSetValue utc_invoicegenerationoverridetype_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("utc_invoicegenerationoverridetype"); }
	set { this.SetPropertyValue<OptionSetValue>("utc_invoicegenerationoverridetype", value, "utc_invoicegenerationoverridetype_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string utc_invoicegenerationoverridetype_Text(IOrganizationService Service)
{
	return this.utc_invoicegenerationoverridetype_OptionSetValue.GetOptionSetText(Service, this, "utc_invoicegenerationoverridetype");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string utc_invoicegenerationoverridetype_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.utc_invoicegenerationoverridetype_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: utc_invoicestartdate</para>
///</summary>
[AttributeLogicalNameAttribute("utc_invoicestartdate")]
public DateTime? utc_invoicestartdate
{
	get { return this.GetPropertyValue<DateTime?>("utc_invoicestartdate"); }
	set { this.SetPropertyValue<DateTime?>("utc_invoicestartdate", value, "utc_invoicestartdate"); }
}
///<summary>
///<para>Logical Name: utc_iscreatedfromabc</para>
///<para>True = Yes</para>
///<para>False = No</para>
///</summary>
[AttributeLogicalNameAttribute("utc_iscreatedfromabc")]
public bool? utc_iscreatedfromabc
{
	get { return this.GetPropertyValue<bool?>("utc_iscreatedfromabc"); }
	set { this.SetPropertyValue<bool?>("utc_iscreatedfromabc", value, "utc_iscreatedfromabc"); }
}
///<summary>
///<para>Logical Name: msdyn_lineorder</para>
///<para>Minimum Value: -2147483648</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_lineorder")]
public int? msdyn_lineorder
{
	get { return this.GetPropertyValue<int?>("msdyn_lineorder"); }
	set { this.SetPropertyValue("msdyn_lineorder", (int?)value, (int)-2147483648, (int)2147483647, "msdyn_lineorder"); }
}
///<summary>
///<para>Logical Name: modifiedby</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedby")]
public EntityReference modifiedby
{
	get { return this.GetPropertyValue<EntityReference>("modifiedby"); }
}
///<summary>
///<para>Logical Name: modifiedonbehalfby</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedonbehalfby")]
public EntityReference modifiedonbehalfby
{
	get { return this.GetPropertyValue<EntityReference>("modifiedonbehalfby"); }
}
///<summary>
///<para>Logical Name: modifiedon</para>
///</summary>
[AttributeLogicalNameAttribute("modifiedon")]
public DateTime? modifiedon
{
	get { return this.GetPropertyValue<DateTime?>("modifiedon"); }
}
///<summary>
///<para>Logical Name: msdyn_name</para>
///<para>Max Length: 200 characters</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_name")]
public string msdyn_name
{
	get { return this.GetPropertyValue<string>("msdyn_name"); }
	set { this.SetPropertyValue("msdyn_name", value, 200, "msdyn_name"); }
}
///<summary>
///<para>Logical Name: ownerid</para>
///</summary>
[AttributeLogicalNameAttribute("ownerid")]
public EntityReference ownerid
{
	get { return this.GetPropertyValue<EntityReference>("ownerid"); }
	set { this.SetPropertyValue<EntityReference>("ownerid", value, "ownerid"); }
}
///<summary>
///<para>Logical Name: owningbusinessunit</para>
///</summary>
[AttributeLogicalNameAttribute("owningbusinessunit")]
public EntityReference owningbusinessunit
{
	get { return this.GetPropertyValue<EntityReference>("owningbusinessunit"); }
}
///<summary>
///<para>Logical Name: owningteam</para>
///</summary>
[AttributeLogicalNameAttribute("owningteam")]
public EntityReference owningteam
{
	get { return this.GetPropertyValue<EntityReference>("owningteam"); }
}
///<summary>
///<para>Logical Name: owninguser</para>
///</summary>
[AttributeLogicalNameAttribute("owninguser")]
public EntityReference owninguser
{
	get { return this.GetPropertyValue<EntityReference>("owninguser"); }
}
///<summary>
///<para>Logical Name: msdyn_pricelist</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_pricelist")]
public EntityReference msdyn_pricelist
{
	get { return this.GetPropertyValue<EntityReference>("msdyn_pricelist"); }
	set { this.SetPropertyValue<EntityReference>("msdyn_pricelist", value, "msdyn_pricelist"); }
}
///<summary>
///<para>Logical Name: msdyn_product</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_product")]
public EntityReference msdyn_product
{
	get { return this.GetPropertyValue<EntityReference>("msdyn_product"); }
	set { this.SetPropertyValue<EntityReference>("msdyn_product", value, "msdyn_product"); }
}
///<summary>
///<para>Logical Name: msdyn_quantity</para>
///<para>Minimum Value: 0</para>
///<para>Maximum Value: 1000000000</para>
///<para>Precision: 2</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_quantity")]
public double? msdyn_quantity
{
	get { return this.GetPropertyValue<double?>("msdyn_quantity"); }
	set { this.SetPropertyValue("msdyn_quantity", (double?)value, (double)0, (double)1000000000, "msdyn_quantity"); }
}
///<summary>
///<para>Logical Name: overriddencreatedon</para>
///</summary>
[AttributeLogicalNameAttribute("overriddencreatedon")]
public DateTime? overriddencreatedon
{
	get { return this.GetPropertyValue<DateTime?>("overriddencreatedon"); }
	set { this.SetPropertyValue<DateTime?>("overriddencreatedon", value, "overriddencreatedon"); }
}
/// <summary>
///Logical Name: statecode
/// </summary>
[AttributeLogicalNameAttribute("statecode")]
public eStatus? statecode
{
	get
	{
		if (statecode_OptionSetValue != null) { return (eStatus)statecode_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.statecode_OptionSetValue = new OptionSetValue((int)value); }
		else this.statecode_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: statecode</para>
///</summary>
[AttributeLogicalNameAttribute("statecode")]
public OptionSetValue statecode_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("statecode"); }
	set { this.SetPropertyValue<OptionSetValue>("statecode", value, "statecode_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string statecode_Text(IOrganizationService Service)
{
	return this.statecode_OptionSetValue.GetOptionSetText(Service, this, "statecode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string statecode_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.statecode_OptionSetValue.Value);
}
/// <summary>
///Logical Name: statuscode
/// </summary>
[AttributeLogicalNameAttribute("statuscode")]
public eStatusReason? statuscode
{
	get
	{
		if (statuscode_OptionSetValue != null) { return (eStatusReason)statuscode_OptionSetValue.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.statuscode_OptionSetValue = new OptionSetValue((int)value); }
		else this.statuscode_OptionSetValue = null;
	}
}
///<summary>
///<para>Logical Name: statuscode</para>
///</summary>
[AttributeLogicalNameAttribute("statuscode")]
public OptionSetValue statuscode_OptionSetValue
{
	get { return this.GetPropertyValue<OptionSetValue>("statuscode"); }
	set { this.SetPropertyValue<OptionSetValue>("statuscode", value, "statuscode_OptionSetValue"); }
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="Service">CRM Organization Service</param>
/// <returns></returns>
public string statuscode_Text(IOrganizationService Service)
{
	return this.statuscode_OptionSetValue.GetOptionSetText(Service, this, "statuscode");
}
/// <summary>
/// Retrieves the current value's text in the user's language.
/// </summary>
/// <param name="AttributeMetadata">The attribute metadata previously retrieved using the 'GetAttributeMetadata' extension method on the IOrganizationService object.</param>
/// <returns></returns>
public string statuscode_Text(EnumAttributeMetadata AttributeMetadata)
{
	return AttributeMetadata.GetOptionSetText(this.statuscode_OptionSetValue.Value);
}
///<summary>
///<para>Logical Name: timezoneruleversionnumber</para>
///<para>Minimum Value: -1</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("timezoneruleversionnumber")]
public int? timezoneruleversionnumber
{
	get { return this.GetPropertyValue<int?>("timezoneruleversionnumber"); }
	set { this.SetPropertyValue("timezoneruleversionnumber", (int?)value, (int)-1, (int)2147483647, "timezoneruleversionnumber"); }
}
///<summary>
///<para>Logical Name: msdyn_unit</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_unit")]
public EntityReference msdyn_unit
{
	get { return this.GetPropertyValue<EntityReference>("msdyn_unit"); }
	set { this.SetPropertyValue<EntityReference>("msdyn_unit", value, "msdyn_unit"); }
}
///<summary>
///<para>Logical Name: msdyn_unitamount</para>
///<para>Minimum Value: 0</para>
///<para>Maximum Value: 1000000000</para>
///<para>Precision: 2</para>
///</summary>
public decimal? msdyn_unitamount
{
	get
	{
		if (msdyn_unitamountMoney != null) { return msdyn_unitamountMoney.Value; }
		return null;
	}
	set
	{
		if (value != null) { this.msdyn_unitamountMoney = new Money(value.Value); }
		else this.msdyn_unitamountMoney = null;
	}
}
///<summary>
///<para>Logical Name: msdyn_unitamount</para>
///<para>Minimum Value: 0</para>
///<para>Maximum Value: 1000000000</para>
///<para>Precision: 2</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_unitamount")]
public Money msdyn_unitamountMoney
{
	get { return this.GetPropertyValue<Money>("msdyn_unitamount"); }
	set { this.SetPropertyValue("msdyn_unitamount", (Money)value, (decimal)0, (decimal)1000000000, "msdyn_unitamountMoney"); }
}
///<summary>
///<para>Logical Name: msdyn_unitamount_base</para>
///<para>Minimum Value: -922337203685477</para>
///<para>Maximum Value: 922337203685477</para>
///<para>Precision: 2</para>
///</summary>
public decimal? msdyn_unitamount_base
{
	get
	{
		if (msdyn_unitamount_baseMoney != null) { return msdyn_unitamount_baseMoney.Value; }
		return null;
	}
}
///<summary>
///<para>Logical Name: msdyn_unitamount_base</para>
///<para>Minimum Value: -922337203685477</para>
///<para>Maximum Value: 922337203685477</para>
///<para>Precision: 2</para>
///</summary>
[AttributeLogicalNameAttribute("msdyn_unitamount_base")]
public Money msdyn_unitamount_baseMoney
{
	get { return this.GetPropertyValue<Money>("msdyn_unitamount_base"); }
}
///<summary>
///<para>Logical Name: utcconversiontimezonecode</para>
///<para>Minimum Value: -1</para>
///<para>Maximum Value: 2147483647</para>
///</summary>
[AttributeLogicalNameAttribute("utcconversiontimezonecode")]
public int? utcconversiontimezonecode
{
	get { return this.GetPropertyValue<int?>("utcconversiontimezonecode"); }
	set { this.SetPropertyValue("utcconversiontimezonecode", (int?)value, (int)-1, (int)2147483647, "utcconversiontimezonecode"); }
}
///<summary>
///<para>Logical Name: versionnumber</para>
///</summary>
[AttributeLogicalNameAttribute("versionnumber")]
public int? versionnumber
{
	get { return this.GetPropertyValue<int?>("versionnumber"); }
}


        /// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_ActivityPointers</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_ActivityPointers (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "activitypointer", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_ActivityPointers</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_ActivityPointers (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "activitypointer", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Annotations</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Annotations (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "annotation", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Annotations</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Annotations (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "annotation", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Appointments</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Appointments (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "appointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Appointments</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Appointments (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "appointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_AsyncOperations</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_AsyncOperations (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "asyncoperation", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_AsyncOperations</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_AsyncOperations (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "asyncoperation", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_BulkDeleteFailures</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_BulkDeleteFailures (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "bulkdeletefailure", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_BulkDeleteFailures</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_BulkDeleteFailures (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "bulkdeletefailure", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_connections1</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_connections1 (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "connection", "record1id", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_connections1</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_connections1 (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "connection", "record1id", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_connections2</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_connections2 (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "connection", "record2id", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_connections2</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_connections2 (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "connection", "record2id", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_DuplicateBaseRecord</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_DuplicateBaseRecord (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "baserecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_DuplicateBaseRecord</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_DuplicateBaseRecord (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "baserecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_DuplicateMatchingRecord</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_DuplicateMatchingRecord (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "duplicaterecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_DuplicateMatchingRecord</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_DuplicateMatchingRecord (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "duplicaterecord", "duplicaterecordid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Emails</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Emails (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "email", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Emails</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Emails (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "email", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Faxes</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Faxes (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "fax", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Faxes</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Faxes (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "fax", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>invoicedetail (Agreement Invoice Product)</b></para>
/// <para>Schema Name: msdyn_msdyn_agreementinvoiceproduct_invoicedetail_AgreementInvoiceProduct</para>
/// </summary>
public List<invoicedetail> msdyn_msdyn_agreementinvoiceproduct_invoicedetail_AgreementInvoiceProduct (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<invoicedetail>(Service, this.Id, "invoicedetail", "msdyn_agreementinvoiceproduct", Columns); }
/// <summary>
/// <para><b>invoicedetail (Agreement Invoice Product)</b></para>
/// <para>Schema Name: msdyn_msdyn_agreementinvoiceproduct_invoicedetail_AgreementInvoiceProduct</para>
/// </summary>
public List<invoicedetail> msdyn_msdyn_agreementinvoiceproduct_invoicedetail_AgreementInvoiceProduct (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities<invoicedetail>(Service, this.Id, "invoicedetail", "msdyn_agreementinvoiceproduct", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Letters</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Letters (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "letter", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Letters</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Letters (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "letter", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_MailboxTrackingFolders</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_MailboxTrackingFolders (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "mailboxtrackingfolder", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_MailboxTrackingFolders</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_MailboxTrackingFolders (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "mailboxtrackingfolder", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_msdyn_bookingalerts</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_msdyn_bookingalerts (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "msdyn_bookingalert", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_msdyn_bookingalerts</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_msdyn_bookingalerts (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "msdyn_bookingalert", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_PhoneCalls</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_PhoneCalls (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "phonecall", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_PhoneCalls</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_PhoneCalls (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "phonecall", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_PrincipalObjectAttributeAccesses</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_PrincipalObjectAttributeAccesses (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "principalobjectattributeaccess", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_PrincipalObjectAttributeAccesses</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_PrincipalObjectAttributeAccesses (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "principalobjectattributeaccess", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_ProcessSession</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_ProcessSession (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "processsession", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_ProcessSession</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_ProcessSession (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "processsession", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_RecurringAppointmentMasters</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_RecurringAppointmentMasters (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "recurringappointmentmaster", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_RecurringAppointmentMasters</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_RecurringAppointmentMasters (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "recurringappointmentmaster", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_ServiceAppointments</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_ServiceAppointments (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "serviceappointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_ServiceAppointments</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_ServiceAppointments (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "serviceappointment", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_SocialActivities</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_SocialActivities (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "socialactivity", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_SocialActivities</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_SocialActivities (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "socialactivity", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_SyncErrors</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_SyncErrors (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "syncerror", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_SyncErrors</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_SyncErrors (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "syncerror", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Tasks</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Tasks (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "task", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_Tasks</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_Tasks (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "task", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_UserEntityInstanceDatas</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_UserEntityInstanceDatas (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "userentityinstancedata", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_UserEntityInstanceDatas</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_UserEntityInstanceDatas (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "userentityinstancedata", "objectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: utc_msdyn_agreementinvoiceproduct_utc_agreementbulkcreation_AgreementInvoiceProduct</para>
/// </summary>
public List<Entity> utc_msdyn_agreementinvoiceproduct_utc_agreementbulkcreation_AgreementInvoiceProduct (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_agreementbulkcreation", "utc_agreementinvoiceproduct", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: utc_msdyn_agreementinvoiceproduct_utc_agreementbulkcreation_AgreementInvoiceProduct</para>
/// </summary>
public List<Entity> utc_msdyn_agreementinvoiceproduct_utc_agreementbulkcreation_AgreementInvoiceProduct (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_agreementbulkcreation", "utc_agreementinvoiceproduct", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: utc_msdyn_agreementinvoiceproduct_utc_agreementinvoiceproductbilling_AgreementInvoiceProduct</para>
/// </summary>
public List<Entity> utc_msdyn_agreementinvoiceproduct_utc_agreementinvoiceproductbilling_AgreementInvoiceProduct (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_agreementinvoiceproductbilling", "utc_agreementinvoiceproduct", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: utc_msdyn_agreementinvoiceproduct_utc_agreementinvoiceproductbilling_AgreementInvoiceProduct</para>
/// </summary>
public List<Entity> utc_msdyn_agreementinvoiceproduct_utc_agreementinvoiceproductbilling_AgreementInvoiceProduct (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_agreementinvoiceproductbilling", "utc_agreementinvoiceproduct", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: utc_msdyn_agreementinvoiceproduct_utc_changelog_AgreementInvoiceProduct</para>
/// </summary>
public List<Entity> utc_msdyn_agreementinvoiceproduct_utc_changelog_AgreementInvoiceProduct (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_changelog", "utc_agreementinvoiceproduct", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: utc_msdyn_agreementinvoiceproduct_utc_changelog_AgreementInvoiceProduct</para>
/// </summary>
public List<Entity> utc_msdyn_agreementinvoiceproduct_utc_changelog_AgreementInvoiceProduct (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_changelog", "utc_agreementinvoiceproduct", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_utc_changeownerrequests</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_utc_changeownerrequests (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_changeownerrequest", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_utc_changeownerrequests</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_utc_changeownerrequests (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_changeownerrequest", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_utc_defectrereports</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_utc_defectrereports (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_defectrereport", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_utc_defectrereports</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_utc_defectrereports (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_defectrereport", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_utc_notetooffices</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_utc_notetooffices (IOrganizationService Service, params string[] Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_notetooffice", "regardingobjectid", Columns); }
/// <summary>
/// <para><b>Entity ()</b></para>
/// <para>Schema Name: msdyn_agreementinvoiceproduct_utc_notetooffices</para>
/// </summary>
public List<Entity> msdyn_agreementinvoiceproduct_utc_notetooffices (IOrganizationService Service, ColumnSet Columns) { return BaseProxyClass.GetRelatedOneToManyEntities(Service, this.Id, "utc_notetooffice", "regardingobjectid", Columns); }


        

        

        public enum eInvoiceBillingType
{
	///<summary><para>Advance</para>
	///<para>Value = 959600000</para></summary>
	[Description("Advance")]
	Advance = 959600000, 
	///<summary><para>Arrears</para>
	///<para>Value = 959600001</para></summary>
	[Description("Arrears")]
	Arrears = 959600001
}
public enum eInvoiceGenerationOverrideType
{
	///<summary><para>N/A- Generate Invoice on Due Date</para>
	///<para>Value = 959600002</para></summary>
	[Description("N/A- Generate Invoice on Due Date")]
	N_A_GenerateInvoiceOnDueDate = 959600002, 
	///<summary><para>X Days Before</para>
	///<para>Value = 959600000</para></summary>
	[Description("X Days Before")]
	XDaysBefore = 959600000, 
	///<summary><para>X Days After</para>
	///<para>Value = 959600001</para></summary>
	[Description("X Days After")]
	XDaysAfter = 959600001
}
public enum eStatus
{
	///<summary><para>Active</para>
	///<para>Value = 0</para></summary>
	[Description("Active")]
	Active = 0, 
	///<summary><para>Inactive</para>
	///<para>Value = 1</para></summary>
	[Description("Inactive")]
	Inactive = 1
}
public enum eStatusReason
{
	///<summary><para>Active</para>
	///<para>Value = 1</para></summary>
	[Description("Active")]
	Active_Active = 1, 
	///<summary><para>Inactive</para>
	///<para>Value = 2</para></summary>
	[Description("Inactive")]
	Inactive_Inactive = 2
}
public void SetState(IOrganizationService Service, eStatus State, eStatusReason Status)
{
	Service.SetState(this, (int)State, (int)Status);
}
public async System.Threading.Tasks.Task SetStateAsync(IOrganizationService Service, eStatus State, eStatusReason Status)
{
	 await Service.SetStateAsync(this, (int)State, (int)Status);
}


        public static class Properties
{
	/// <summary><para>utc_invoicefrequencyname</para>
	/// <para>utc_invoicefrequencyname</para></summary>
	public const string utc_invoicefrequencyname = "utc_invoicefrequencyname";
	/// <summary><para>owneridtype</para>
	/// <para>owneridtype</para></summary>
	public const string owneridtype = "owneridtype";
	/// <summary><para>utc_changetypename</para>
	/// <para>utc_changetypename</para></summary>
	public const string utc_changetypename = "utc_changetypename";
	/// <summary><para>modifiedbyname</para>
	/// <para>modifiedbyname</para></summary>
	public const string modifiedbyname = "modifiedbyname";
	/// <summary><para>owneridname</para>
	/// <para>owneridname</para></summary>
	public const string owneridname = "owneridname";
	/// <summary><para>createdonbehalfbyyominame</para>
	/// <para>createdonbehalfbyyominame</para></summary>
	public const string createdonbehalfbyyominame = "createdonbehalfbyyominame";
	/// <summary><para>utc_customerequipmentname</para>
	/// <para>utc_customerequipmentname</para></summary>
	public const string utc_customerequipmentname = "utc_customerequipmentname";
	/// <summary><para>utc_changereasonname</para>
	/// <para>utc_changereasonname</para></summary>
	public const string utc_changereasonname = "utc_changereasonname";
	/// <summary><para>createdonbehalfbyname</para>
	/// <para>createdonbehalfbyname</para></summary>
	public const string createdonbehalfbyname = "createdonbehalfbyname";
	/// <summary><para>createdbyyominame</para>
	/// <para>createdbyyominame</para></summary>
	public const string createdbyyominame = "createdbyyominame";
	/// <summary><para>msdyn_unitname</para>
	/// <para>msdyn_unitname</para></summary>
	public const string msdyn_unitname = "msdyn_unitname";
	/// <summary><para>msdyn_agreementname</para>
	/// <para>msdyn_agreementname</para></summary>
	public const string msdyn_agreementname = "msdyn_agreementname";
	/// <summary><para>owneridyominame</para>
	/// <para>owneridyominame</para></summary>
	public const string owneridyominame = "owneridyominame";
	/// <summary><para>msdyn_productname</para>
	/// <para>msdyn_productname</para></summary>
	public const string msdyn_productname = "msdyn_productname";
	/// <summary><para>createdbyname</para>
	/// <para>createdbyname</para></summary>
	public const string createdbyname = "createdbyname";
	/// <summary><para>modifiedonbehalfbyname</para>
	/// <para>modifiedonbehalfbyname</para></summary>
	public const string modifiedonbehalfbyname = "modifiedonbehalfbyname";
	/// <summary><para>msdyn_pricelistname</para>
	/// <para>msdyn_pricelistname</para></summary>
	public const string msdyn_pricelistname = "msdyn_pricelistname";
	/// <summary><para>transactioncurrencyidname</para>
	/// <para>transactioncurrencyidname</para></summary>
	public const string transactioncurrencyidname = "transactioncurrencyidname";
	/// <summary><para>msdyn_agreementinvoicesetupname</para>
	/// <para>msdyn_agreementinvoicesetupname</para></summary>
	public const string msdyn_agreementinvoicesetupname = "msdyn_agreementinvoicesetupname";
	/// <summary><para>modifiedbyyominame</para>
	/// <para>modifiedbyyominame</para></summary>
	public const string modifiedbyyominame = "modifiedbyyominame";
	/// <summary><para>modifiedonbehalfbyyominame</para>
	/// <para>modifiedonbehalfbyyominame</para></summary>
	public const string modifiedonbehalfbyyominame = "modifiedonbehalfbyyominame";
	/// <summary><para>Agreement</para>
	/// <para>msdyn_agreement</para></summary>
	public const string msdyn_agreement = "msdyn_agreement";
	/// <summary><para>Agreement Invoice Product</para>
	/// <para>msdyn_agreementinvoiceproductid</para></summary>
	public const string msdyn_agreementinvoiceproductid = "msdyn_agreementinvoiceproductid";
	/// <summary><para>Agreement Invoice Setup</para>
	/// <para>msdyn_agreementinvoicesetup</para></summary>
	public const string msdyn_agreementinvoicesetup = "msdyn_agreementinvoicesetup";
	/// <summary><para>Billing Type</para>
	/// <para>utc_billingtype</para></summary>
	public const string utc_billingtype = "utc_billingtype";
	/// <summary><para>Bypass Cascade Ownership</para>
	/// <para>utc_bypasscascadeownership</para></summary>
	public const string utc_bypasscascadeownership = "utc_bypasscascadeownership";
	/// <summary><para>Change Comments</para>
	/// <para>utc_changecomments</para></summary>
	public const string utc_changecomments = "utc_changecomments";
	/// <summary><para>Change Reason</para>
	/// <para>utc_changereason</para></summary>
	public const string utc_changereason = "utc_changereason";
	/// <summary><para>Change Type</para>
	/// <para>utc_changetype</para></summary>
	public const string utc_changetype = "utc_changetype";
	/// <summary><para>Created By</para>
	/// <para>createdby</para></summary>
	public const string createdby = "createdby";
	/// <summary><para>Created By (Delegate)</para>
	/// <para>createdonbehalfby</para></summary>
	public const string createdonbehalfby = "createdonbehalfby";
	/// <summary><para>Created On</para>
	/// <para>createdon</para></summary>
	public const string createdon = "createdon";
	/// <summary><para>Currency</para>
	/// <para>transactioncurrencyid</para></summary>
	public const string transactioncurrencyid = "transactioncurrencyid";
	/// <summary><para>Customer Equipment</para>
	/// <para>utc_customerequipment</para></summary>
	public const string utc_customerequipment = "utc_customerequipment";
	/// <summary><para>Exchange Rate</para>
	/// <para>exchangerate</para></summary>
	public const string exchangerate = "exchangerate";
	/// <summary><para>Import Sequence Number</para>
	/// <para>importsequencenumber</para></summary>
	public const string importsequencenumber = "importsequencenumber";
	/// <summary><para>Invoice Frequency</para>
	/// <para>utc_invoicefrequency</para></summary>
	public const string utc_invoicefrequency = "utc_invoicefrequency";
	/// <summary><para>Invoice Generation Override (Hidden)</para>
	/// <para>utc_invoicegenerationoverride</para></summary>
	public const string utc_invoicegenerationoverride = "utc_invoicegenerationoverride";
	/// <summary><para>Invoice Generation Override Type (Hidden)</para>
	/// <para>utc_invoicegenerationoverridetype</para></summary>
	public const string utc_invoicegenerationoverridetype = "utc_invoicegenerationoverridetype";
	/// <summary><para>Invoice Start Date</para>
	/// <para>utc_invoicestartdate</para></summary>
	public const string utc_invoicestartdate = "utc_invoicestartdate";
	/// <summary><para>Is Created from ABC (Hidden)</para>
	/// <para>utc_iscreatedfromabc</para></summary>
	public const string utc_iscreatedfromabc = "utc_iscreatedfromabc";
	/// <summary><para>Line Order</para>
	/// <para>msdyn_lineorder</para></summary>
	public const string msdyn_lineorder = "msdyn_lineorder";
	/// <summary><para>Modified By</para>
	/// <para>modifiedby</para></summary>
	public const string modifiedby = "modifiedby";
	/// <summary><para>Modified By (Delegate)</para>
	/// <para>modifiedonbehalfby</para></summary>
	public const string modifiedonbehalfby = "modifiedonbehalfby";
	/// <summary><para>Modified On</para>
	/// <para>modifiedon</para></summary>
	public const string modifiedon = "modifiedon";
	/// <summary><para>Name</para>
	/// <para>msdyn_name</para></summary>
	public const string msdyn_name = "msdyn_name";
	/// <summary><para>Owner</para>
	/// <para>ownerid</para></summary>
	public const string ownerid = "ownerid";
	/// <summary><para>Owning Business Unit</para>
	/// <para>owningbusinessunit</para></summary>
	public const string owningbusinessunit = "owningbusinessunit";
	/// <summary><para>Owning Team</para>
	/// <para>owningteam</para></summary>
	public const string owningteam = "owningteam";
	/// <summary><para>Owning User</para>
	/// <para>owninguser</para></summary>
	public const string owninguser = "owninguser";
	/// <summary><para>Price List</para>
	/// <para>msdyn_pricelist</para></summary>
	public const string msdyn_pricelist = "msdyn_pricelist";
	/// <summary><para>Product</para>
	/// <para>msdyn_product</para></summary>
	public const string msdyn_product = "msdyn_product";
	/// <summary><para>Quantity</para>
	/// <para>msdyn_quantity</para></summary>
	public const string msdyn_quantity = "msdyn_quantity";
	/// <summary><para>Record Created On</para>
	/// <para>overriddencreatedon</para></summary>
	public const string overriddencreatedon = "overriddencreatedon";
	/// <summary><para>Status</para>
	/// <para>statecode</para></summary>
	public const string statecode = "statecode";
	/// <summary><para>Status Reason</para>
	/// <para>statuscode</para></summary>
	public const string statuscode = "statuscode";
	/// <summary><para>Time Zone Rule Version Number</para>
	/// <para>timezoneruleversionnumber</para></summary>
	public const string timezoneruleversionnumber = "timezoneruleversionnumber";
	/// <summary><para>Unit</para>
	/// <para>msdyn_unit</para></summary>
	public const string msdyn_unit = "msdyn_unit";
	/// <summary><para>Unit Amount</para>
	/// <para>msdyn_unitamount</para></summary>
	public const string msdyn_unitamount = "msdyn_unitamount";
	/// <summary><para>Unit Amount (Base)</para>
	/// <para>msdyn_unitamount_base</para></summary>
	public const string msdyn_unitamount_base = "msdyn_unitamount_base";
	/// <summary><para>UTC Conversion Time Zone Code</para>
	/// <para>utcconversiontimezonecode</para></summary>
	public const string utcconversiontimezonecode = "utcconversiontimezonecode";
	/// <summary><para>Version Number</para>
	/// <para>versionnumber</para></summary>
	public const string versionnumber = "versionnumber";
}

    }
}
